#!/bin/sh

#!/bin/sh

NAME="service"
DESCRIPTION="commands for services."

_invoke() {
  "$1" "$2"
}

add() {
  while true; do
    echo -n "Service name (required) : "
    read name
    if [ "$name" != "" ]; then
      break
    fi
  done

  echo -n "Service description : "
  read description

  while true; do
    echo -n "Service directory (required) : "
    read directory
    if [ "$directory" != "" ]; then
      break
    fi
  done

  while true; do
    echo -n "Service command (required) : "
    read command
    if [ "$command" != "" ]; then
      break
    fi
  done

  [ ! -d "./services/" ] && mkdir "./services"

  echo "#!/bin/sh

NAME='$name'
DESCRIPTION='$description'
DIRECTORY='$directory'
COMMAND='$command'

  " >>"./services/$name"
}

list() {
  for entry in "./services"/*; do
    . "$entry"
    echo "\e[1;33m$NAME\e[0m : $DESCRIPTION (directory: \e[1;32m$DIRECTORY\e[0m, command: \e[1;32m$COMMAND\e[0m)"
  done
}

remove() {
  unlink "./services/$1"
}

start() {
  . "./services/$1"

  echo Running : "\e[1;32m$NAME\e[0m"
  echo "\e[1;32mExecuting $COMMAND in $DIRECTORY\e[0m"
  cd $DIRECTORY && $COMMAND &
}
