#!/bin/sh

NAME="service-run"
DESCRIPTION="Run server for a particular service, pass service name to start the server"

_invoke() {
  . "./services/$1"

  echo Running : "\e[1;32m$NAME\e[0m"
  cd $DIRECTORY && $COMMAND &
}
