#!/bin/sh

NAME="service-add"
DESCRIPTION="Add new Service to the system"

_invoke() {
  echo "Service name ?"
  read name
  echo "Service description ?"
  read description
  echo "Service directory ?"
  read directory
  echo "Service command ?"
  read command

  echo "#!/bin/sh

NAME='$name'
DESCRIPTION='$description'
DIRECTORY='$directory'
COMMAND='$command'

  " >>"./services/$name"
}
