#!/bin/sh

NAME="servers"
DESCRIPTION="Running server for the all the services."

_invoke() {

  echo "You are running $0"

  for entry in "./services"/*; do
    . "$entry"
    echo Running : "\e[1;32m$NAME\e[0m"
    echo "\e[1;32mExecuting $COMMAND in $DIRECTORY\e[0m"
    cd $DIRECTORY && $COMMAND &
    done
}
