#!/bin/sh

NAME="service-list"
DESCRIPTION="Listing all the available services."

_invoke() {
  for entry in "./services"/*; do
    . "$entry"
    echo "\e[1;33m$NAME\e[0m : $DESCRIPTION (directory: \e[1;32m$DIRECTORY\e[0m, command: \e[1;32m$COMMAND\e[0m)"
  done
}
