#!/bin/sh

#!/bin/sh

NAME="service"
DESCRIPTION="commands for services."

_invoke() {
  "$1" "$2"
}


add() {
  echo "Service name ?"
  read name
  echo "Service description ?"
  read description
  echo "Service directory ?"
  read directory
  echo "Service command ?"
  read command

  echo "#!/bin/sh

NAME='$name'
DESCRIPTION='$description'
DIRECTORY='$directory'
COMMAND='$command'

  " >>"./services/$name"
}

list() {
  for entry in "./services"/*; do
    . "$entry"
    echo "\e[1;33m$NAME\e[0m : $DESCRIPTION (directory: \e[1;32m$DIRECTORY\e[0m, command: \e[1;32m$COMMAND\e[0m)"
  done
}

remove() {
  unlink "./services/$1"
}

capturePid () {
      echo "#!/bin/sh

PID=$!" >> "./process/$NAME"
}


start() {
  . "./services/$1"

  echo Running : "\e[1;32m$NAME\e[0m"
  echo "\e[1;32mExecuting $COMMAND in $DIRECTORY\e[0m"
  cd $DIRECTORY && $COMMAND &
  capturePid &
}



